import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-gradient-to-br from-[#0a0a0a] via-[#111111] to-[#0f0f0f]`}
      >
        <Toaster
          position="top-right"
          toastOptions={{
            className: "bg-[#0f0f0f] text-gray-300 border border-gray-700",
            style: { fontFamily: "var(--font-geist-mono)" },
          }}
        />
        {children}
      </body>
    </html>
  );
}
